//query
at.(*selectForUpdateExecutor).ExecContext (select_for_update_executor.go:113) github.com/seata/seata-go/pkg/datasource/sql/exec/at
at.(*ATExecutor).ExecWithNamedValue (at_executor.go:76) github.com/seata/seata-go/pkg/datasource/sql/exec/at
sql.(*ATConn).QueryContext.func2 (conn_at.go:70) github.com/seata/seata-go/pkg/datasource/sql
sql.(*ATConn).createNewTxOnExecIfNeed (conn_at.go:188) github.com/seata/seata-go/pkg/datasource/sql
sql.(*ATConn).QueryContext (conn_at.go:54) github.com/seata/seata-go/pkg/datasource/sql

sql.ctxDriverQuery (ctxutil.go:48) database/sql
sql.(*DB).queryDC.func1 (sql.go:1748) database/sql
sql.withLock (sql.go:3405) database/sql
sql.(*DB).queryDC (sql.go:1743) database/sql
sql.(*DB).query (sql.go:1726) database/sql
sql.(*DB).QueryContext.func1 (sql.go:1704) database/sql
sql.(*DB).retry (sql.go:1538) database/sql
sql.(*DB).QueryContext (sql.go:1703) database/sql

main.selectForUpdateData (select_for_update.go:30) main
tm.WithGlobalTx (transaction_executor.go:80) github.com/seata/seata-go/pkg/tm
main.sampleSelectForUpdate (select_for_update.go:49) main
main.main (main.go:42) main
runtime.main (proc.go:250) runtime
runtime.goexit (asm_amd64.s:1598) runtime
 - 异步堆栈跟踪
<autogenerated>:2